---
- include: copy_yaml_file.yml

- name: Ensure seed dir exist
  file:
    state: directory
    path: "/root/seed"
    mode: 0755
  delegate_to: localhost

- name: Decompress seed files
  unarchive:
    src: "/root/home/files/{{ seed_data_archive_name }}"
    dest: "/backend"
    mode: 0755
    remote_src: true
  delegate_to: localhost

- name: Seeding data
  shell: "cd /backend && dart bin/cli.dart dbutil seed -d -c"
  delegate_to: localhost
