---
- include: copy_yaml_file.yml

- name: Remove old seeds directory
  file:
    path: "/backend/res/seeds"
    state: absent
  delegate_to: localhost
  become: true

- name: Create fresh migrations folder
  file:
    path: "/backend/res/seeds"
    state: directory
  delegate_to: localhost
  become: true

- name: Decompress seed files
  unarchive:
    src: "/root/home/files/{{ seed_data_archive_name }}"
    dest: "/backend"
    mode: 0755
    remote_src: true
  delegate_to: localhost

- name: Seeding data
  shell: "cd /backend && dart bin/cli.dart dbutil seed -d -o -c"
  delegate_to: localhost
