---
- name: Create and run restic server
  hosts: resticserver
  gather_facts: false
  become_user: root
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/backup_default.yml
  roles:
    - backup_restic_server