---
- name: Deploy server
  hosts: backendservers
  gather_facts: true
  user: root
  serial: 1
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/database_default.yml
  roles:
    - postgres_db