---
- name: Deploy server
  hosts: servers
  gather_facts: true
  user: root
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/deploy_configs/server_deploy_default.yml
    - vars/deploy_configs/jayjah_default.yml
    - vars/deploy_configs/orthofit_default.yml
    - vars/database_default.yml
  roles:
    - deploy_server
    - docker_clear
    - log