---
- name: Docker test
  hosts: servers
  gather_facts: false
  become: true
  become_user: root
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/docker_default.yml
    - vars/metrics_default.yml
  roles:
    - docker
    - docker_registries