---
- name: Create prometheus, grafana server and collect metrics from clients
  hosts: metricsserver
  gather_facts: false
  user: root
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/metrics_default.yml
    - vars/deploy_configs/server_deploy_default.yml
  roles:
    - metrics_prometheus_server