---
- name: Setting up server
  hosts: servers
  gather_facts: false
  become: true
  become_user: root
  vars_files:
    - vars/default.yml
    - vars/settings.yml
    - vars/database_default.yml
  roles:
    - ufw
    - user
    - ssh
    - dart
    - docker
    - postgres_db
    - redis_db
    - docker_clear
    - log