---
- name: Full update and upgrade, includes kernel update and reboot
  hosts: servers
  become: true
  become_user: root
  vars_files:
    - vars/default.yml
  roles:
    - os_update
    - docker_clear
    - log