---
- name: Start cadvisor container (os metrics)
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    state: started
    recreate: false
    restart: false
    restart_policy: unless-stopped
    published_ports:
      - "{{ cadvisor_metrics_port }}:8080"
    output_logs: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      labels: postgres
      max-file: '3'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # to collect data from docker on macos host:
      #- /var/run/docker.sock:/var/run/docker.sock:rw
  when: enable_metrics == True

- name: Start node-exporter container (os metrics)
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    state: started
    recreate: false
    restart: false
    restart_policy: unless-stopped
    published_ports:
      - "{{ node_metrics_port }}:9100"
    output_logs: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      labels: postgres
      max-file: '3'
    when: enable_metrics == True