---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  when: permit_root_login == True

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Disable challenge response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
    state: present
  notify: restart ssh

- name: Make sshd_config only readable
  file:
    path: /etc/ssh/sshd_config
    mode: '0444'
    state: file
  notify: restart ssh

