enable_redis: False
permit_root_login: False
enable_postgres: True
enable_metrics: True
postgres_version: 10
postgres_container_name:
postgres_db_name:
postgres_db_user:
postgres_db_password:
postgres_container_port:
postgres_metrics_port:
server_container_name:
server_port:
cadvisor_metrics_port:
node_metrics_port: