---
- name: Installation and configuration of restic-client
  block:
    - name: install restic
      apt: name=restic state=latest update_cache=yes
      become: true

    - name: update restic
      shell: restic self-update
      become: true

    - name: create backup directory
      file:
        state: directory
        path: "/home/{{ username }}/backup"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: copy backup application to remote host
      copy:
        src: /root/backup_runtime.sh
        dest: "/home/{{ username }}/backup/backup_runtime.sh"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: install restic client config to remote host
      template:
        src: templates/.restic_backup.json.j2
        dest: "/home/{{ username }}/backup/.restic_backup.json"
        force: yes
        #owner: "{{ username }}"
        #group: "{{ username }}"
        #mode: "0755"

    - name: remove old hive data (hive.hive)
      file:
        path: "/home/{{ username }}/backup/vaultbox.hive"
        state: absent

    - name: remove old hive data (hive.lock)
      file:
        path: "/home/{{ username }}/backup/vaultbox.lock"
        state: absent

    - name: run backup application preparation script
      shell:
        chdir: "/home/{{ username }}/backup/"
        cmd: ./backup_runtime.sh prepare --path .restic_backup.json
      args:
        executable: /bin/bash
      become: no
      become_user: "{{ username }}"

    - name: ensure restic file has correct permissions (hive.hive)
      file:
        state: file
        path: "/home/{{ username }}/backup/vaultbox.hive"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: ensure restic file has correct permissions (hive.lock)
      file:
        state: file
        path: "/home/{{ username }}/backup/vaultbox.lock"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: remove restic client config
      file:
        path: "/home/{{ username }}/backup/.restic_backup.json"
        state: absent

    - name: init restic
      shell: "restic init -r rest:{{ repo_url }}"
      become: true
      environment:
        RESTIC_PASSWORD: "{{ restic_client_password }}"
      ignore_errors: yes

    - name: make backup
      shell:
        chdir: "/home/{{ username }}/backup/"
        cmd: "./backup_runtime.sh make --name {{ name }}"
      args:
        executable: /bin/bash
      become: no
      become_user: "{{ username }}"