---
- name: Enable firewall
  ufw: state=enabled policy=deny logging='off'

- name: Allow HTTP
  ufw: rule=allow port=80 proto=tcp
  when: inventory_hostname != 'metricsandbackups'

- name: Allow HTTPS
  ufw: rule=allow port=443 proto=tcp
  when: inventory_hostname != 'metricsandbackups'

- name: Limit SSH
  ufw: rule=limit port=22 proto=tcp
  
- name: Limit OpenSSH
  ufw: rule=limit name=OpenSSH

- name: Allow server port
  ufw: rule=allow port={{ server_port | quote }} proto=tcp
  when: inventory_hostname != 'metricsandbackups'

- name: Allow all access from subnet network to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - "{{ default_server_network_ip_range }}"
