---
- name: Ensure restic backup directory exist
  file:
    state: directory
    path: /tmp/backups
    mode: 0755
# server should only be rechable in private network, NOT public
#- name: Allow restic server port
#  ufw: rule=allow port="{{ restic_port | string }}" proto=tcp
#  become: true
- name: Create for each repo an user for restic server to enable access
  htpasswd:
    path: /tmp/backups/.htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ restic_repos }}"
  no_log: True

- name: Start restic server container
  docker_container:
    name: restic_server
    image: "restic/rest-server:latest"
    state: started
    recreate: false
    restart: true
    #pull: yes
    restart_policy: unless-stopped
    published_ports:
      - "{{ restic_port }}:8000"
    volumes:
      - /tmp/backups:/data
    interactive: yes
    tty: yes
    output_logs: yes
    #log_driver: json-file
    #log_options:
    #  max-size: 10m
    #  max-file: '3'
    #  labels: restic
    env:
      OPTIONS: "--private-repos --max-size 6500000000 --prometheus --path /data" # 6.5gb

- name: Create users in restic server itself for each project
  shell: "docker exec -it restic_server create_user {{ item.name }} {{ item.password }}"
  loop: "{{ restic_repos }}"
  no_log: True