---
- name: Login at a docker-registry
  docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: yes
    state: present
  loop: '{{ docker_registries }}'
  no_log: True