---
- name: Copy server repo archive to remote host and decompress it
  unarchive:
    src: /root/server.tar.gz
    dest: "/home/{{ username }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    remote_src: false

- name: Create server config yaml file
  template:
    src: templates/server_deploy/config.yaml.j2
    dest: "/home/{{ username }}/backend/config.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: yes

- name: Build server docker image (jayjah/server-dart)
  docker_image:
    name: "{{ backend_docker_image_name }}"
    build:
      path: "/home/{{ username }}/backend"
      dockerfile: docker/Dockerfile
      nocache: yes
      pull: no
      target: "{{ server_build_target_stage }}"
      args:
        ISOLATES: "{{ server_isolates }}"
        PORTS: "{{ server_port }}"
    source: build

- name: Remove compressed archive
  file:
    path: "/home/{{ username }}/backend/server.tar.gz"
    state: absent
  become: true