---
- name: Remove old server container
  docker_container:
    name: "{{ server_container_name }}-{{ name }}"
    state: absent

- name: Remove old server image
  docker_image:
    name: "{{ backend_docker_image_name }}"
    state: absent

- name: Clear docker, prune docker system
  shell: docker system prune -a -f
  args:
    executable: /bin/bash
  become_user: "{{ username }}"