---
- name: Copy public archive to remote host and decompress it
  unarchive:
    src: "/root/home/files/{{ server_public_archive_name }}"
    dest: "/home/{{ username }}"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    remote_src: false

- name: Get images from public dir
  find:
    paths: "/home/{{ username }}/public/images"
    file_type: file
  register: images

#- name: images from archive file
#  debug:
#    msg: "{{ item.path | basename }}"
#  loop: "{{ images.files }}"

- name: Copy new images to backend directory
  copy:
    src: "/home/{{ username }}/public/images/{{ item.path | basename }}"
    dest: "/home/{{ username }}/backend/public/images/{{ item.path | basename }}"
    force: true
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    remote_src: true
  loop: "{{ images.files }}"

- name: Get static files from public dir
  find:
    paths: "/home/{{ username }}/public/files"
    file_type: file
  register: staticfiles

- name: Copy new static files to backend directory
  copy:
    src: "/home/{{ username }}/public/files/{{ item.path | basename }}"
    dest: "/home/{{ username }}/backend/public/files/{{ item.path | basename }}"
    force: yes
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0755
    remote_src: true
  loop: "{{ staticfiles.files }}"

- name: Get web files from public dir
  find:
    paths: "/home/{{ username }}/public/web"
    file_type: file
  register: webfiles

- name: Copy new web files to backend directory
  copy:
    src: "/home/{{ username }}/public/web/{{ item.path | basename }}"
    dest: "/home/{{ username }}/backend/public/web/{{ item.path | basename }}"
    force: yes
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0755
    remote_src: true
  loop: "{{ webfiles.files }}"

- name: Remove public archive
  file:
    path: "/home/{{ username }}/public"
    state: absent
  become: true