---
- name: Ensure backend directory exist
  file:
    state: directory
    path: "/home/{{ username }}/backend"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    force: yes

- name: Ensure backend/public directory exist
  file:
    state: directory
    path: "/home/{{ username }}/backend/public"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    force: yes

- name: Ensure backend/public/images directory exist
  file:
    state: directory
    path: "/home/{{ username }}/backend/public/images"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    force: yes

- name: Ensure backend/public/files exist
  file:
    state: directory
    path: "/home/{{ username }}/backend/public/files"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    force: yes

- name: Ensure backend/public/web exist
  file:
    state: directory
    path: "/home/{{ username }}/backend/public/web"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0777
    force: yes

- name: Create server keys_config env file
  template:
    src: templates/server_deploy/keys_config.env.j2
    dest: "/home/{{ username }}/backend/keys_config.env"
    owner: "{{ username }}"
    group: "{{ username_uid }}"
    mode: 0700
    force: yes