---
- name: Copy image archive to remote host and decompress it
  copy:
    src: "/root/home/files/{{ server_archive_name }}"
    dest: "/home/{{ username }}/backend/{{ server_archive_name }}.tar"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Load image
  docker_image:
    name: "{{ server_container_name }}-{{ name }}"
    load_path: "/home/{{ username }}/backend/{{ server_archive_name }}.tar"
    source: load

- name: Remove image archive
  file:
    name: "/home/{{ username }}/backend/{{ server_archive_name }}.tar"
    state: absent
  become: true