---
- name: Ensure backend directory exist
  file:
    state: directory
    path: "/home/{{ username }}/backend"
    mode: 0755

- name: Create server keys_config env file
  template:
    src: templates/server_deploy/keys_config.env.j2
    dest: "/home/{{ username }}/backend/keys_config.env"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
    force: yes

- name: Remove old containers
  include: clear_stop_running_server.yml

- name: Run server container
  include: run_from_registry.yml

- name: Run promtail container
  include: run_promtail.yml

- name: Copy public static files
  include: copy_public_files.yml
  when: copy_public_files == True

- name: Remove env file
  file:
    state: absent
    path: "/home/{{ username }}/backend/keys_config.env"
