---
- name: Ensure backend directory exist
  file:
    state: directory
    path: "/home/{{ username }}/backend"
    mode: 0755

- name: Remove old containers
  include: remove_images.yml

- name: Build server image from repository
  include: build_docker_image.yml
  when: build_from_repo == True

- name: Load server image from archive
  include: load_from_archive.yml
  when: load_from_archive == True

- include: copy_env_file.yml

- name: Load and run server image from registry
  include: load_from_registry.yml
  when: load_from_registry == True

- name: Run server from local image
  include: run_server_from_local_image.yml
  when: load_from_registry == False

- name: Deploy public static files
  include: copy_public_files.yml
  when: deploy_public_files == True

- name: Remove env file
  file:
    state: absent
    path: "/home/{{ username }}/backend/keys_config.env"

- name: Remove env file from home
  file:
    state: absent
    path: "/home/{{ username }}/keys_config.env"
