---
- name: Remove old containers
  include_role:
    name: remove_images

- name: Build server image from repository
  include_role:
    name: build_docker_image
  when: build_from_archive == False

- name: Load server image from archive
  include_role:
    name: load_from_archive
  when: build_from_archive == True

#- name: Create server keys_config yaml file
#  template:
#    src: templates/server_deploy/keys_config.yaml.j2
#    dest: "/home/{{ username }}/dart_backend/keys_config.yaml"
#    owner: "{{ username }}"
#    group: "{{ username }}"
#    mode: 0700

- name: Run server docker container (jayjah/server-dart)
  docker_container:
    name: server-dart
    image: "{{ server_container_name }}"
    state: started
    recreate: true
    restart: false
    restart_policy: unless-stopped
    published_ports:
      - "{{ server_port }}:{{ server_port }}"
    volumes:
      - "/home/{{ username }}/dart_server/public:/app/public"
    output_logs: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      labels: server-dart
      max-file: '3'
    env:
      POSTGRES_DB: "{{ postgres_db_name }}"
