---
- name: Run server
  docker_container:
    name: "{{ server_container_name }}-{{ name }}"
    image: "{{ backend_docker_image_name }}"
    state: started
    recreate: true
    restart: false
    restart_policy: unless-stopped
    published_ports:
      - "{{ server_port }}:{{ server_port }}"
    volumes:
      - "/home/{{ username }}/backend/public:/app/public"
    env_file: "/home/{{ username }}/backend/keys_config.env"
    output_logs: yes
    interactive: yes
    tty: yes
    #log_driver: json-file
    #log_options:
    #  max-size: 10m
    #  labels: backend-dart
    #  max-file: '3'