---
- name: Run server docker image from registry
  docker_container:
    name: "{{ server_container_name }}-{{ name }}"
    image: "{{ server_registry_url }}{{ server_registry_image_name }}"
    recreate: true
    restart: false
    restart_policy: unless-stopped
    published_ports:
      - "{{ server_port }}:{{ server_port }}"
    mounts:
      - read_only=no,type=bind,source="/home/{{ username }}/backend/public",target=/app/public
    env_file: "/home/{{ username }}/backend/keys_config.env"
    user: "{{ username }}"
    output_logs: yes
    interactive: yes
    tty: yes
    pull: yes
    log_driver: "json-file"
    log_options:
    #  loki-url: "http://{{ metrics_ip }}:{{ loki_port }}/loki/api/v1/push"
    #  mode: "non-blocking"
    #  loki-retries: '5'
      max-size: '10m'
      labels: "backend"
      max-file: '3'
    #  loki-batch-size: '400'