---
- name: Install promtail-server-config.yaml file
  template:
    src: templates/prometheus/promtail-server-config.yaml.j2
    dest: "/home/{{ username }}/promtail-config.yaml"
    force: yes

- name: Remove old promtail container
  docker_container:
    name: promtail-{{ inventory_hostname }}
    state: absent

- name: Run promtail docker container
  docker_container:
    name: promtail-{{ inventory_hostname }}
    image: "grafana/promtail:2.3.0"
    recreate: true
    restart: false
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - /home/{{ username }}/promtail-config.yaml:/mnt/config/promtail-config.yaml:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/log/nginx/:/var/log/nginx/:ro
    command:
      - "--config.file=/mnt/config/promtail-config.yaml"
    output_logs: yes
    interactive: yes
    tty: yes
    pull: yes
    log_driver: "json-file"
    log_options:
      #  loki-url: "http://{{ metrics_ip }}:{{ loki_port }}/loki/api/v1/push"
      #  mode: "non-blocking"
      #  loki-retries: '5'
      max-size: '10m'
      labels: "promtail"
      max-file: '3'
    #  loki-batch-size: '400'