---
- name: Add dart apt-key
  shell: "sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'"
  args:
    executable: /bin/bash
  become: true

- name: Add dart repo
  shell: "sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'"
  args:
    executable: /bin/bash
  become: true

- name: Install dart
  apt: update_cache=yes name=dart state=latest