---
- name: Update system
  apt: update_cache=yes force_apt_get=yes upgrade=dist state=latest

- name: Clear apt
  apt: force_apt_get=yes cache_valid_time=3600 upgrade=full state=latest autoclean=yes autoremove=yes
  
- name: Reboot remote host
  reboot:
    connect_timeout: 80

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'aptitude', 'git-core', 'git', 'ufw', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'apache2-utils', 'snap']
