---
- name: Generate Docker daemon configuration with loki file
  template:
    src: templates/daemon-loki.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
    #mode: 0700
    force: yes

- name: Start docker system service, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
    name: docker
  ignore_errors: yes

- name: Start docker service
  service: name=docker state=started