---
- name: Allow incoming access from port 22 to db port
  ufw:
    rule: allow
    direction: in
    proto: any
    from_port: "22"
    to_port: "{{ postgres_container_port | quote }}"

- name: Allow incoming access to db
  ufw:
    rule: allow
    port: "{{ postgres_container_port | quote }}"

- name: Remove database data directory
  file:
    state: absent
    path: "/home/{{ username }}/database"
  when: delete_old_db_data == True

- name: Ensure database directory exist
  file:
    state: directory
    path: "/home/{{ username }}/database"
    mode: 0755

- name: Start postgres db container
  docker_container:
    name: "{{ postgres_container_name }}-{{ name }}"
    image: "postgres:{{ postgres_version }}"
    state: started
    recreate: yes
    restart: false
    restart_policy: unless-stopped
    volumes:
      - "/home/{{ username }}/database:/var/lib/postgresql/data"
    published_ports: 
      - "{{ postgres_container_port }}:5432"
    interactive: yes
    tty: yes
    output_logs: yes
    #log_driver: json-file
    #log_options:
    #  max-size: 10m
    #  labels: postgres
    #  max-file: '3'
    env:
      POSTGRES_DB: "{{ postgres_db_name }}"
      POSTGRES_PASSWORD: "{{ postgres_db_password }}"
      POSTGRES_USER: "{{ postgres_db_user }}"
      PGDATA: '/var/lib/postgresql/data/pgdata'
  when: inventory_hostname != 'metricsandbackups'
  no_log: True
