---
- name: Allow incoming access from port 22 to db port
  ufw:
    rule: allow
    direction: in
    proto: any
    from_port: "22"
    to_port: "{{ postgres_container_port }}"

- name: Allow incoming access from server port to db port
  ufw:
    rule: allow
    direction: in
    proto: any
    from_port: "{{ server_port }}"
    to_port: "{{ postgres_container_port }}"

- name: Start postgres db container
  docker_container:
    name: "{{ postgres_container_name }}-{{ name }}"
    image: "postgres:{{ postgres_version }}"
    state: started
    recreate: false
    restart: false
    restart_policy: unless-stopped
    published_ports: 
      - "{{ postgres_container_port }}:5432"
    output_logs: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      labels: postgres
      max-file: '3'
    env:
      POSTGRES_DB: "{{ postgres_db_name }}"
      POSTGRES_PASSWORD: "{{ postgres_db_password }}"
      POSTGRES_USER: "{{ postgres_db_user }}"
  when: enable_postgres == True and inventory_hostname != 'metricsandbackups'
